preware: Drop public/private and legacy registration
Since this no longer works with latest luna-service2 from OSE.

Fixes:
/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/core2-64-webos-linux/org.webosports.service.ipkg/2.0.0-2+gitAUTOINC+1fe4a701f2-r0/git/oe-service/src/luna_service.h:27:1: error: unknown type name 'LSPalmService'
   27 | LSPalmService   *serviceHandle;
      | ^~~~~~~~~~~~~
In file included from /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/core2-64-webos-linux/org.webosports.service.ipkg/2.0.0-2+gitAUTOINC+1fe4a701f2-r0/git/oe-service/src/ipkgservice.h:23,
                 from /mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/core2-64-webos-linux/org.webosports.service.ipkg/2.0.0-2+gitAUTOINC+1fe4a701f2-r0/git/oe-service/src/ipkgservice.c:23:
/mnt/5ba5d474-0b2d-49d6-a5a6-9de20c3ac967/kirkstone-qt6/webos-ports/tmp-glibc/work/core2-64-webos-linux/org.webosports.service.ipkg/2.0.0-2+gitAUTOINC+1fe4a701f2-r0/git/oe-service/src/luna_methods.h:25:23: error: unknown type name 'LSPalmService'
   25 | bool register_methods(LSPalmService *serviceHandle, LSError lserror);
      |                       ^~~~~~~~~~~~~

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>